#!/usr/bin/env bash
# Loops from 1 to 10 and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

string="Best School"
i=1

while (( i <= 10 )); do
	if [[ $i = 4 ]]; then
		echo "bad luck"
	elif [[ $i = 8 ]]; then
		echo "good luck"
	else
		echo "$string"
	fi
	((i++))
done
