#!/usr/bin/env bash
# Configure container to run `nginx` as user `nginx` listening on all active IPs on port `8080`
sed -i "s/#user.*/user nginx;/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod u+rwx /etc/nginx/nginx.conf
chown nginx:nginx /usr/sbin/nginx
service apache2 stop
pkill apache2
su -c "service nginx start" nginx
